export ARTIFACTORY="https://qartifactory-edge.qualcomm.com/artifactory/qsc_releases/software/chip/component/gfx-adreno.le.0.0"
export TAG="260318"
export DISTRO="prebuilt_resolute"
export PACKAGE_NAME="qcom-adreno_1.855.2_arm64.tar.gz"


